/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Onur Atakan ULUSOY
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

public class alarm_clock extends javax.swing.JFrame implements Runnable{
    String program_name = "Alarm Clock by ONUR";
    String selection_ringtone, ringtone_name;
    
    FileInputStream fileInputStream;
    BufferedInputStream bufferedInputStream;
    Player player;
    long all;
    
    
    String current_timeStr;
    
    
    
    String alarmhour, alarmminute, alarmsecond;
    
    

    int snooze_hour = 0;
    int snooze_minute = 0;
    int snooze_second = 0;
    


    
    
    
    /**
     * Creates new form alarm_clock
     */
    public alarm_clock() {
        initComponents();
        setLocationRelativeTo(null);
        //jPanel1.setVisible(false);
        hide_show_a_settings.setVisible(false);
        jPanel2.setVisible(false);
                
        snooze_alarm_button.setVisible(false);
        stop_alarm_button.setVisible(false);
        
        main_text_2.setVisible(false);
        sounding_an_alarm.setVisible(false);
        
        jPanel1.setSize(360,70);
        
        Thread ct =new Thread(this);
        ct.start();
        
        
        

        ImageIcon icon = new ImageIcon(getClass().getResource("/clock.png"));
        setIconImage(icon.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        listen_to_ringtone = new javax.swing.JToggleButton();
        ringtone_name_label = new javax.swing.JLabel();
        alarm_save_button = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        current_time_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        alarm_hour_box = new javax.swing.JComboBox<>();
        alarm_minute_box = new javax.swing.JComboBox<>();
        alarm_second_box = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        start_button = new javax.swing.JToggleButton();
        hide_show_a_settings = new javax.swing.JToggleButton();
        set_ringtone_button = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        main_text = new javax.swing.JLabel();
        alarm_time_label = new javax.swing.JLabel();
        stop_alarm_button = new javax.swing.JToggleButton();
        snooze_alarm_button = new javax.swing.JToggleButton();
        main_text_2 = new javax.swing.JLabel();
        sounding_an_alarm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Alarm Clock by ONUR");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(2147, 2147));
        setPreferredSize(new java.awt.Dimension(370, 278));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));
        jPanel1.setMinimumSize(new java.awt.Dimension(370, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 240));

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(260, 55));

        listen_to_ringtone.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        listen_to_ringtone.setText("Listen to ringtone");
        listen_to_ringtone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listen_to_ringtoneActionPerformed(evt);
            }
        });

        ringtone_name_label.setForeground(new java.awt.Color(200, 200, 200));
        ringtone_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ringtone_name_label.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(listen_to_ringtone)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ringtone_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(listen_to_ringtone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ringtone_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alarm_save_button.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        alarm_save_button.setText("Alarm save");
        alarm_save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarm_save_buttonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Current Time:");

        current_time_label.setBackground(new java.awt.Color(97, 206, 112));
        current_time_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        current_time_label.setForeground(new java.awt.Color(97, 206, 112));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alarm Clock :");

        alarm_hour_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));
        alarm_hour_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarm_hour_boxActionPerformed(evt);
            }
        });

        alarm_minute_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "00" }));
        alarm_minute_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarm_minute_boxActionPerformed(evt);
            }
        });

        alarm_second_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "00" }));

        jLabel3.setForeground(new java.awt.Color(130, 130, 130));
        jLabel3.setText("Hour");

        jLabel5.setForeground(new java.awt.Color(130, 130, 130));
        jLabel5.setText("Minute");

        jLabel6.setForeground(new java.awt.Color(130, 130, 130));
        jLabel6.setText("Second");

        start_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        start_button.setText("Show alarm settings");
        start_button.setMaximumSize(new java.awt.Dimension(100, 25));
        start_button.setMinimumSize(new java.awt.Dimension(100, 25));
        start_button.setPreferredSize(new java.awt.Dimension(100, 25));
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });

        hide_show_a_settings.setText("Hide alarm settings");
        hide_show_a_settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hide_show_a_settingsActionPerformed(evt);
            }
        });

        set_ringtone_button.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        set_ringtone_button.setText("Set ringtone");
        set_ringtone_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_ringtone_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hide_show_a_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(start_button, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(set_ringtone_button)
                        .addGap(61, 61, 61)
                        .addComponent(alarm_save_button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(current_time_label, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(alarm_hour_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(alarm_minute_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel3)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel5)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alarm_second_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hide_show_a_settings))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(current_time_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alarm_hour_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alarm_minute_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alarm_second_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alarm_save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set_ringtone_button))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 240);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(26, 26, 26));
        jPanel3.setMinimumSize(new java.awt.Dimension(360, 190));
        jPanel3.setPreferredSize(new java.awt.Dimension(360, 190));

        main_text.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        main_text.setForeground(new java.awt.Color(97, 206, 112));
        main_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        main_text.setText("Welcome");

        alarm_time_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alarm_time_label.setForeground(new java.awt.Color(26, 26, 26));
        alarm_time_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        stop_alarm_button.setText("Stop alarm");
        stop_alarm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop_alarm_buttonActionPerformed(evt);
            }
        });

        snooze_alarm_button.setText("Snooze alarm");
        snooze_alarm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snooze_alarm_buttonActionPerformed(evt);
            }
        });

        main_text_2.setForeground(new java.awt.Color(255, 255, 255));
        main_text_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        main_text_2.setText("Sounding an alarm");

        sounding_an_alarm.setForeground(new java.awt.Color(255, 255, 255));
        sounding_an_alarm.setText("Hours/Minutes/Seconds");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(snooze_alarm_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stop_alarm_button))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(main_text, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(alarm_time_label, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(main_text_2)))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(sounding_an_alarm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(main_text, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_text_2)
                .addGap(12, 12, 12)
                .addComponent(alarm_time_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sounding_an_alarm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stop_alarm_button)
                    .addComponent(snooze_alarm_button))
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 70, 360, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void set_ringtone_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_ringtone_buttonActionPerformed

        if(set_ringtone_button.getText().equals("Set ringtone")){
            set_ringtone();
            jPanel2.setVisible(true);
            set_ringtone_button.setText("Close ringtone picker");
        } else if (set_ringtone_button.getText().equals("Close ringtone picker")){
            jPanel2.setVisible(false);
            set_ringtone_button.setText("Set ringtone");
        }
        
        
        if (!selection_ringtone.equals(null)){
            ringtone_name_label.setText("Ringtone Name : " + ringtone_name);
        }
                
    }//GEN-LAST:event_set_ringtone_buttonActionPerformed

    private void alarm_save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarm_save_buttonActionPerformed
        alarmhour = alarm_hour_box.getSelectedItem().toString();
        alarmminute = alarm_minute_box.getSelectedItem().toString();
        alarmsecond = alarm_second_box.getSelectedItem().toString();
        
        if (ringtone_name_label.getText() != ""){
            String alarmtimestr = alarmhour +"."+ alarmminute +"."+ alarmsecond;
            System.out.println(alarmtimestr);
            alarm_time(Integer.valueOf(alarmhour),Integer.valueOf(alarmminute),Integer.valueOf(alarmsecond));
            JOptionPane.showMessageDialog(null, "Alarm recorded", program_name, JOptionPane.INFORMATION_MESSAGE);
            main_text.setText("There is an alarm installed");
            main_text_2.setVisible(true);
            sounding_an_alarm.setVisible(true);
            
            jPanel1.setSize(360,70);
            hide_show_a_settings.setText("Show alarm settings");
        } else {
            JOptionPane.showMessageDialog(null, "You didn't choose ringtone", program_name, JOptionPane.INFORMATION_MESSAGE);

        }
        
    }//GEN-LAST:event_alarm_save_buttonActionPerformed

    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
        if (start_button.getText().equals("Show alarm settings")){
            main_text.setText("No alarm installed");
            hide_show_a_settings.setVisible(true);

            jPanel1.setSize(360,240);
            
            start_button.setVisible(false);
        }
    }//GEN-LAST:event_start_buttonActionPerformed

    private void listen_to_ringtoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listen_to_ringtoneActionPerformed
        try {
            if(listen_to_ringtone.getText().equals("Listen to ringtone")){
                playing_ringtone();
                listen_to_ringtone.setText("Stop ringtone");
            } else if (listen_to_ringtone.getText().equals("Stop ringtone")){
                player.close();
                listen_to_ringtone.setText("Listen to ringtone");
            }
   
            
        } catch (IOException ex) {
            Logger.getLogger(alarm_clock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listen_to_ringtoneActionPerformed

    private void hide_show_a_settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hide_show_a_settingsActionPerformed
        if (hide_show_a_settings.getText().equals("Hide alarm settings")){
            jPanel1.setSize(360,70);
            hide_show_a_settings.setText("Show alarm settings");
        } else if(hide_show_a_settings.getText().equals("Show alarm settings")){
            jPanel1.setSize(360,240);
            hide_show_a_settings.setText("Hide alarm settings");
        }
    }//GEN-LAST:event_hide_show_a_settingsActionPerformed

    private void alarm_minute_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarm_minute_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alarm_minute_boxActionPerformed

    private void stop_alarm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop_alarm_buttonActionPerformed
        main_text.setText("No alarm installed");
        player.close();
        snooze_alarm_button.setVisible(false);
        stop_alarm_button.setVisible(false);
        
    }//GEN-LAST:event_stop_alarm_buttonActionPerformed

    private void snooze_alarm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snooze_alarm_buttonActionPerformed
        snooze_time ();
        main_text.setText("Snooze for 5 minutes");
        snooze_alarm_button.setVisible(false);
        stop_alarm_button.setVisible(false);
        
    }//GEN-LAST:event_snooze_alarm_buttonActionPerformed

    private void alarm_hour_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarm_hour_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alarm_hour_boxActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            int closing_message = JOptionPane.showConfirmDialog(null, "Do you want to close ?", program_name, JOptionPane.INFORMATION_MESSAGE );
 
            if (closing_message == JOptionPane.YES_OPTION){
            System.exit(0);
            
            } else if (closing_message == JOptionPane.NO_OPTION){
                
            }
    }//GEN-LAST:event_formWindowClosing
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alarm_clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alarm_clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alarm_clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alarm_clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alarm_clock().setVisible(true);
            }
        });
    }

    public void set_ringtone(){
        
        JFileChooser jfc = new JFileChooser();
        int selection_ringtone_int = jfc.showOpenDialog(null); 
        
       if (selection_ringtone_int==JFileChooser.APPROVE_OPTION) {
        File ringtone = jfc.getSelectedFile();
        
        selection_ringtone = ringtone.getAbsolutePath();
        ringtone_name = jfc.getSelectedFile().getName();
        System.out.println(ringtone_name);   
       } else if (selection_ringtone_int==JFileChooser.CANCEL_OPTION) {
           JOptionPane.showMessageDialog(null, "You didn't choose ringtone");
       }
        
    }
    
    
    public void playing_ringtone() throws IOException{

        try {
            fileInputStream = new FileInputStream(new File(selection_ringtone));
            bufferedInputStream = new BufferedInputStream(fileInputStream);
            player = new Player(bufferedInputStream);
            all = fileInputStream.available();
            
            
            new Thread(){
            public void run(){
                try {
                    player.play();
                } catch (JavaLayerException ex) {
                    Logger.getLogger(alarm_clock.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            }.start();
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(alarm_clock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JavaLayerException ex) {
            Logger.getLogger(alarm_clock.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }
    
    public void alarm_time(final int hour, final int minute, final int second){
        Thread at = new Thread(){
            public void run(){
                int a = 0;
                while (a == 0){

                    Calendar c = Calendar.getInstance();
                    int h = c.get(Calendar.HOUR_OF_DAY);
                    int m = c.get(Calendar.MINUTE);
                    int s = c.get(Calendar.SECOND);
                    
                    int atlh = (hour) - (h);
                    String atlhstr = String.valueOf(atlh);
                    int atlm = (minute) - (m);
                    String atlmstr = String.valueOf(atlm);                    
                    int atls = (second) - (s);
                    String atlsstr = String.valueOf(atls);                    
                    
                    alarm_time_label.setText(atlhstr +"."+ atlmstr +"."+ atlsstr);
                        
    
                    if (hour==h && minute==m && second==s){
                        try {
                            playing_ringtone();
                        } catch (IOException ex) {
                            Logger.getLogger(alarm_clock.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                        
                        main_text.setText("ALARM !!!");
                        
                        snooze_alarm_button.setVisible(true);
                        stop_alarm_button.setVisible(true);
                        break;
                    }
                }
                
            }
        };
        at.start();
    }
    
    
    public void snooze_time (){
        snooze_hour = Integer.valueOf(alarmhour);
        snooze_minute = Integer.valueOf(alarmminute);
        snooze_second = Integer.valueOf(alarmsecond);
        
        snooze_minute = snooze_minute+5;
        if(snooze_minute == 60){
            snooze_hour = snooze_hour+1;
            snooze_minute = 0;
        }
        else if(snooze_minute == 61){
            snooze_hour = snooze_hour+1;
            snooze_minute = 1;
        }
        else if(snooze_minute == 62){
            snooze_hour = snooze_hour+1;
            snooze_minute = 2;
        }
        else if(snooze_minute == 63){
            snooze_hour = snooze_hour+1;
            snooze_minute = 3;
        }
        else if(snooze_minute == 64){
            snooze_hour = snooze_hour+1;
            snooze_minute = 4;
        }
        
        alarm_time(snooze_hour, snooze_minute, snooze_second);
        
        player.close();
        
        System.out.println(snooze_hour +"."+ snooze_minute +"."+ snooze_second);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alarm_hour_box;
    private javax.swing.JComboBox<String> alarm_minute_box;
    private javax.swing.JToggleButton alarm_save_button;
    private javax.swing.JComboBox<String> alarm_second_box;
    private javax.swing.JLabel alarm_time_label;
    private javax.swing.JLabel current_time_label;
    private javax.swing.JToggleButton hide_show_a_settings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton listen_to_ringtone;
    private javax.swing.JLabel main_text;
    private javax.swing.JLabel main_text_2;
    private javax.swing.JLabel ringtone_name_label;
    private javax.swing.JToggleButton set_ringtone_button;
    private javax.swing.JToggleButton snooze_alarm_button;
    private javax.swing.JLabel sounding_an_alarm;
    private javax.swing.JToggleButton start_button;
    private javax.swing.JToggleButton stop_alarm_button;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true){
            Calendar c = Calendar.getInstance();
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("HH:mm:ss");
            
            Date date = c.getTime();
            
            
            current_timeStr = simpleDateFormat.format(date);
            
            
            current_time_label.setText(current_timeStr);
            
            

        }
    }
}
